name: Run tests on project

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "v1.26.2"

      - name: Run tests
        run: deno test --allow-all
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "e1da9aed-04f3-4ce6-8f67-b59db824e5c2"
          heroku_app_name: "housing-system"
          heroku_email: "bachthy94@gmail.com"